apiVersion: v1
kind: Secret
metadata:
  name: bibliotheque-secrets
  namespace: bibliotheque
type: Opaque
stringData:
  jwt-secret: "{{JWT_SECRET}}"
---
apiVersion: v1
kind: Secret
metadata:
  name: bibliotheque-db-secrets
  namespace: bibliotheque
type: Opaque
stringData:
  db-host: "ep-delicate-shadow-a4rahkg5-pooler.us-east-1.aws.neon.tech"
  db-port: "5432"
  db-name: "neondb"
  db-user: "{{DB_USER}}"
  db-password: "{{DB_PASSWORD}}"