apiVersion: v1
kind: Service
metadata:
  name: bibliotheque-microbooks-service
  namespace: bibliotheque
spec:
  type: NodePort
  ports:
  - port: 3003
    targetPort: 3003
    nodePort: 30083
  selector:
    app: bibliotheque-microbooks
