apiVersion: v1
kind: Service
metadata:
  name: bibliotheque-microbooks-service
  namespace: bibliotheque
spec:
  type: NodePort
  ports:
  - port: 3002
    targetPort: 3002
    nodePort: 30082
  selector:
    app: bibliotheque-microbooks
